
import os


srcs = '''
  lesson01/utils.cc
  lesson01/main.cc
'''

flags = ['-g', '-Werror']
libs = ['GL', 'GLU', 'glut']


Program(os.path.join('..', 'bin', 'lesson01'), Split(srcs), CPPPATH=['.'],
    LIBS=libs, CPPFLAGS=flags)
