
import os


appname = 'lesson03'
srcs = '''
  lesson03/utils.cc
  lesson03/main.cc
'''

flags = ['-g', '-Werror']
libs = ['GL', 'GLU', 'glut']


Program(os.path.join('..', 'bin', appname), Split(srcs), CPPPATH=['.'],
    LIBS=libs, CPPFLAGS=flags)
